### ISSUE TITLE
パックの動きに関する処理の実装

### ISSUE THREAD

**Issue by lasaqna** [Nitech-Jaeger/air-hockey#32]
[パックとプレイヤーの衝突判定の方法](https://drive.google.com/file/d/13DMP_uuJ5MoPVZl5Cok5_iIGIdIaHkMD/view?usp=drive_link)

**Comment by MurakawaTakuya** [comment]
@lasaqna 
https://github.com/Nitech-Jaeger/air-hockey/issues/32#issue-2522413915

権限ついてなくて見れないよー
